### ISSUE TITLE
License File Won't Stay

### ISSUE THREAD

**Issue by patbro-zz** [DocuWare/Intellix#2]
I have installed this in a test environment. All appears to work, other than when installing the license file.... The license is accepted when installed, after closing the browser and re-opening the license is lost.

**Comment by chweidling** [comment]
Probably it is a bug in the UI. If the service is working, i.e. accepting files, then we should fix the UI.

**Comment by chweidling** [comment]
The UI is fixed. A container update deploys the fixed UI.

**Comment by patbro-zz** [comment]
After using the ./update-intellix PS script, I am still seeing the same result.

**Comment by chweidling** [comment]
Reopen this until we have the container-based setup in place.

**Comment by chweidling** [comment]
In the branch "dac", this issue is addressed.

**Comment by chweidling** [comment]
The license file can be passed on the setup script. This should solve the problem.
